
student_name = input("Please enter your name: ")
student_id = input("Please enter your TP number: ")
marks = int(input("Please enter your marks: "))
grade = input("Please enter your grade: ")
cfpa = float(input("Please enter your CGPA: "))
print()
print("Your details are as follows:\n")
print("Name: "+student_name)
print("TP number: " + student_id)
print("Marks:" + str(marks))
print("Grade: " + grade)
print("CGPA: ", cfpa)
print("\nThank you for registering")
